/**
 * Canonical object property keys used during decoded-to-normalized mapping.
 *
 * These constants remove hard-coded property-name literals from mapping helpers.
 */
export const PROPERTY_KEY = {
  code: "code",
  codeType: "codeType",
  name: "name",
  address: "address",
  postalCode: "postalCode",
  phone: "phone",
  fax: "fax",
  otherContact: "otherContact",
  department: "department",
  departmentCodeType: "departmentCodeType",
  departmentCode: "departmentCode",
  prefectureCode: "prefectureCode",
  date: "date",
  kanaName: "kanaName",
  kanjiName: "kanjiName",
  sexCode: "sexCode",
  birthDate: "birthDate",
  copayClassCode: "copayClassCode",
  insuranceTypeCode: "insuranceTypeCode",
  insurerNumber: "insurerNumber",
  cardSymbol: "cardSymbol",
  cardNumber: "cardNumber",
  insuredRelationshipCode: "insuredRelationshipCode",
  cardBranchNumber: "cardBranchNumber",
  patientCopayRate: "patientCopayRate",
  insuranceBenefitRate: "insuranceBenefitRate",
  reasonCode: "reasonCode",
  payerNumber: "payerNumber",
  recipientNumber: "recipientNumber",
  occupationalAccidentReasonCode: "occupationalAccidentReasonCode",
  receiptTypeCode: "receiptTypeCode",
  prescriptionDate: "prescriptionDate",
  dispensingDueDate: "dispensingDueDate",
  licenseNumber: "licenseNumber",
  patientAddress: "patientAddress",
  patientPhone: "patientPhone",
  confirmationFlag: "confirmationFlag",
  remainingMedicineConfirmationFlag: "remainingMedicineConfirmationFlag",
  totalCount: "totalCount",
  currentCount: "currentCount",
  totalUseCount: "totalUseCount",
  sequence: "sequence",
  noteType: "noteType",
  text: "text",
  numberType: "numberType",
  number: "number",
  dosageFormCode: "dosageFormCode",
  dosageFormName: "dosageFormName",
  dispensingQuantity: "dispensingQuantity",
  splitDispensingQuantity: "splitDispensingQuantity",
  usageCode: "usageCode",
  usageText: "usageText",
  usageSupplementCode: "usageSupplementCode",
  usageSupplementText: "usageSupplementText",
  convertedAmount: "convertedAmount",
  convertedUnit: "convertedUnit",
  unevenDosingCode: "unevenDosingCode",
  unevenDosingText: "unevenDosingText",
  burdenCategoryCode: "burdenCategoryCode",
  burdenCategoryText: "burdenCategoryText",
  singleDoseAmount: "singleDoseAmount",
  singleDoseUnit: "singleDoseUnit",
  supplementCode: "supplementCode",
  supplementText: "supplementText",
  amount: "amount",
  unit: "unit",
  infoClass: "infoClass",
  potencyFlag: "potencyFlag",
  timesPerDay: "timesPerDay",
  supplementSequence: "supplementSequence",
  supplementClass: "supplementClass",
  supplementUsageCode: "supplementUsageCode",
  firstPublicExpenseBurdenCode: "firstPublicExpenseBurdenCode",
  secondPublicExpenseBurdenCode: "secondPublicExpenseBurdenCode",
  thirdPublicExpenseBurdenCode: "thirdPublicExpenseBurdenCode",
  specialPublicExpenseBurdenCode: "specialPublicExpenseBurdenCode",
  unevenDosingAmount1: "unevenDosingAmount1",
  unevenDosingAmount2: "unevenDosingAmount2",
  unevenDosingAmount3: "unevenDosingAmount3",
  unevenDosingAmount4: "unevenDosingAmount4",
  unevenDosingAmount5: "unevenDosingAmount5",
  unevenDosingCode1: "unevenDosingCode1",
  unevenDosingCode2: "unevenDosingCode2",
  unevenDosingCode3: "unevenDosingCode3",
  unevenDosingCode4: "unevenDosingCode4",
  unevenDosingCode5: "unevenDosingCode5",
} as const;

/**
 * Union of supported mapping property keys.
 */
export type PropertyFieldKey = (typeof PROPERTY_KEY)[keyof typeof PROPERTY_KEY];
